// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(NewsParserDbContext))]
    partial class NewsParserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ArticleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RawArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RejectedByEditorId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("RawArticleId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("articles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ContradictionArticleEntity", b =>
                {
                    b.Property<Guid>("ContradictionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.HasKey("ContradictionId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("contradiction_articles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ContradictionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("IsResolved");

                    b.ToTable("contradictions", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.EventArticleEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WasReclassified")
                        .HasColumnType("boolean");

                    b.HasKey("EventId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("event_articles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FirstSeenAt");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("Status");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.EventUpdateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("FactSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EventId");

                    b.HasIndex("IsPublished");

                    b.ToTable("event_updates", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EditorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneratedContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentPublicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublishTargetId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateContext")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("EditorId");

                    b.HasIndex("EventId");

                    b.HasIndex("ParentPublicationId");

                    b.HasIndex("PublishTargetId");

                    b.HasIndex("Status");

                    b.ToTable("publications", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublishLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExternalMessageId")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("publish_logs", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublishTargetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Platform");

                    b.ToTable("publish_targets", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.RawArticleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Category")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Status");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique();

                    b.ToTable("raw_articles", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.SourceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ArticleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.RawArticleEntity", "RawArticle")
                        .WithOne("Article")
                        .HasForeignKey("Infrastructure.Persistence.Entity.ArticleEntity", "RawArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawArticle");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ContradictionArticleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.ArticleEntity", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entity.ContradictionEntity", "Contradiction")
                        .WithMany("ContradictionArticles")
                        .HasForeignKey("ContradictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Contradiction");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ContradictionEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.EventEntity", "Event")
                        .WithMany("Contradictions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.EventArticleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.ArticleEntity", "Article")
                        .WithMany("EventArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entity.EventEntity", "Event")
                        .WithMany("EventArticles")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.EventUpdateEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.ArticleEntity", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entity.EventEntity", "Event")
                        .WithMany("EventUpdates")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublicationEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.ArticleEntity", "Article")
                        .WithMany("Publications")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Persistence.Entity.UserEntity", "Editor")
                        .WithMany("Publications")
                        .HasForeignKey("EditorId");

                    b.HasOne("Infrastructure.Persistence.Entity.PublicationEntity", "ParentPublication")
                        .WithMany()
                        .HasForeignKey("ParentPublicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Infrastructure.Persistence.Entity.PublishTargetEntity", "PublishTarget")
                        .WithMany("Publications")
                        .HasForeignKey("PublishTargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Editor");

                    b.Navigation("ParentPublication");

                    b.Navigation("PublishTarget");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublishLogEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.PublicationEntity", "Publication")
                        .WithMany("PublishLogs")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.RawArticleEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entity.SourceEntity", "Source")
                        .WithMany("RawArticles")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ArticleEntity", b =>
                {
                    b.Navigation("EventArticles");

                    b.Navigation("Publications");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.ContradictionEntity", b =>
                {
                    b.Navigation("ContradictionArticles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.EventEntity", b =>
                {
                    b.Navigation("Contradictions");

                    b.Navigation("EventArticles");

                    b.Navigation("EventUpdates");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublicationEntity", b =>
                {
                    b.Navigation("PublishLogs");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.PublishTargetEntity", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.RawArticleEntity", b =>
                {
                    b.Navigation("Article");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.SourceEntity", b =>
                {
                    b.Navigation("RawArticles");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entity.UserEntity", b =>
                {
                    b.Navigation("Publications");
                });
#pragma warning restore 612, 618
        }
    }
}
